#!/usr/bin/env python3
"""Generate the boulingua pentagon in every format the platform needs.

    python brand/make_icon.py            this course, from hugo.toml `code`
    python brand/make_icon.py gfl        one code explicitly
    python brand/make_icon.py --all      all 18, into brand/ and brand/icons/
    python brand/make_icon.py --check    regenerate into a temp tree and diff

The mark is one pentagon filled in the language's signature accent. Same shape
for every course, so the family reads as one platform; different colour, so a
course is recognisable at a glance.

WHY THIS WAS REWRITTEN

Seventeen of the eighteen `brand/icon.svg` files in the org were 1,388-byte
matplotlib dumps at viewBox 0 0 72 72, each carrying an RDF block and its own
`<dc:date>` timestamp, and seventeen `brand/icon.png` were 256x256 where the
script asked for 512. They are the output of a superseded version of this
script that nobody re-ran. Persian — the only code generated by the current
version — is the one that is correct. So Persian is the reference and the other
seventeen are regenerated to match it.

Three real defects are fixed here:

1. matplotlib is not byte-reproducible (AGG rasterisation and pHYs/tEXt chunks
   vary by version) and is a heavy dependency for filling a five-sided polygon.
   Pillow at 4x supersample with LANCZOS downsampling replaces it.

2. NOTHING in the org generated `brand/icons/<code>.pdf`. The 34 committed icon
   PDFs carry `/Creator: Matplotlib v3.6.3` and a fixed `/CreationDate`, and no
   script in any repository produces them — they are byte-identical only
   because they came out of one unreproducible run. Without a generator, a
   digest gate over the icon set is not possible, and `\\blgsetlang{pfa}` fails
   at `\\includegraphics` because the eighteenth was never drawn.

3. `site_code()` silently defaulted to "efl" when hugo.toml had no `code` key.
   A wrong default that looks like a working build is worse than a stop: the
   course would have shipped English's green. It is now a hard exit naming the
   file.

Deterministic by construction: the SVG is written by hand rather than dumped by
a plotting library, PNG carries no ancillary chunks, and the PDF has its
/CreationDate and /ID suppressed. Without all three, --check can never pass.
"""
from __future__ import annotations

import argparse
import filecmp
import math
import re
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ACCENTS = ROOT / "data" / "accents.yaml"
PNG_SIZES = {"brand/icon.png": 512, "static/favicon-32.png": 32,
             "static/favicon-16.png": 16, "static/apple-touch-icon.png": 180}
SUPERSAMPLE = 4


def accents() -> list[dict]:
    return yaml.safe_load(ACCENTS.read_text(encoding="utf-8"))


def accent_for(code: str) -> str:
    for a in accents():
        if a.get("code") == code:
            return a["accent"]
    raise SystemExit(f"code '{code}' is not in data/accents.yaml")


def site_code() -> str:
    if len(sys.argv) > 1 and not sys.argv[1].startswith("-"):
        return sys.argv[1]
    cfg = ROOT / "hugo.toml"
    if not cfg.exists():
        cfg = ROOT / "hugo.defaults.toml"
    m = re.search(r'^\s*code\s*=\s*"([^"]+)"', cfg.read_text(encoding="utf-8"), re.M)
    if not m:
        # Never guess. A silent default ships another course's colour and looks
        # like a working build, which is the failure this exit exists to stop.
        raise SystemExit(f"no `code` key in {cfg.name} — set it or pass a code argument")
    return m.group(1)


def pentagon(cx: float, cy: float, r: float) -> list[tuple[float, float]]:
    """Point-up regular pentagon, y increasing downward (SVG/screen convention)."""
    return [(cx + r * math.sin(2 * math.pi * i / 5),
             cy - r * math.cos(2 * math.pi * i / 5)) for i in range(5)]


def svg_for(colour: str) -> str:
    pts = pentagon(50, 52, 42)
    d = " ".join(f"{'M' if i == 0 else 'L'}{x:.2f},{y:.2f}"
                 for i, (x, y) in enumerate(pts)) + " Z"
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'
            f'<path d="{d}" fill="{colour}"/></svg>')


def write_png(path: Path, colour: str, px: int) -> None:
    from PIL import Image, ImageDraw
    n = px * SUPERSAMPLE
    img = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    pts = [(x * n / 100, y * n / 100) for x, y in pentagon(50, 52, 42)]
    ImageDraw.Draw(img).polygon(pts, fill=colour)
    img = img.resize((px, px), Image.LANCZOS)
    path.parent.mkdir(parents=True, exist_ok=True)
    # optimize only; no pnginfo, so no tEXt/pHYs chunks to vary between runs.
    img.save(path, format="PNG", optimize=True)


def write_pdf(path: Path, colour: str) -> None:
    import reportlab.rl_config as rl
    rl.invariant = 1          # fixes /CreationDate and /ID — the whole point
    from reportlab.pdfgen import canvas
    from reportlab.lib.colors import HexColor
    path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(path), pagesize=(100, 100), invariant=1)
    c.setCreator("boulingua make_icon.py")
    c.setProducer("boulingua make_icon.py")
    c.setTitle(path.stem)
    p = c.beginPath()
    # PDF's y axis points up; the pentagon is defined y-down, so flip it.
    pts = [(x, 100 - y) for x, y in pentagon(50, 52, 42)]
    p.moveTo(*pts[0])
    for pt in pts[1:]:
        p.lineTo(*pt)
    p.close()
    c.setFillColor(HexColor(colour))
    c.drawPath(p, stroke=0, fill=1)
    c.showPage()
    c.save()


def emit_one(root: Path, code: str, colour: str) -> list[Path]:
    out = [root / "brand" / "icon.svg"]
    out[0].parent.mkdir(parents=True, exist_ok=True)
    out[0].write_text(svg_for(colour), encoding="utf-8")
    for rel, px in PNG_SIZES.items():
        p = root / rel
        write_png(p, colour, px)
        out.append(p)
    return out


def emit_all(root: Path) -> list[Path]:
    """Every code's icon PDF, plus a per-code SVG for the website map."""
    out = []
    for a in accents():
        code, colour = a["code"], a["accent"]
        pdf = root / "brand" / "icons" / f"{code}.pdf"
        write_pdf(pdf, colour)
        svg = root / "brand" / "icons" / f"{code}.svg"
        svg.write_text(svg_for(colour), encoding="utf-8")
        out += [pdf, svg]
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("code", nargs="?", help="site code; default reads hugo.toml")
    ap.add_argument("--all", action="store_true", help="emit all 18 icon sets")
    ap.add_argument("--check", action="store_true", help="regenerate and diff")
    a = ap.parse_args()

    if a.check:
        tmp = Path(tempfile.mkdtemp(prefix="blgicon-"))
        emit_all(tmp)
        bad = 0
        for gen in sorted((tmp / "brand" / "icons").iterdir()):
            live = ROOT / "brand" / "icons" / gen.name
            if not live.exists():
                print(f"::error::brand/icons/{gen.name} is missing — run make_icon.py --all")
                bad += 1
            elif not filecmp.cmp(gen, live, shallow=False):
                print(f"::error::brand/icons/{gen.name} differs from what tokens produce")
                bad += 1
        if bad:
            print(f"\nFAIL — {bad} icon(s) do not match data/accents.yaml.", file=sys.stderr)
            return 1
        n = len(list((ROOT / "brand" / "icons").glob("*.pdf")))
        print(f"make_icon --check OK — {n} icon PDFs match data/accents.yaml")
        return 0

    if a.all:
        files = emit_all(ROOT)
        codes = len(accents())
        print(f"  {codes} codes → brand/icons/ ({len(files)} files)")
        return 0

    code = a.code or site_code()
    colour = accent_for(code)
    for p in emit_one(ROOT, code, colour):
        print(f"  {p.relative_to(ROOT)}")
    print(f"  code={code} accent={colour}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
