#!/usr/bin/env python3
"""Generate every colour, type, space and radius artefact from tokens.yaml.

    python design/build_tokens.py            write the artefacts
    python design/build_tokens.py --check    regenerate into memory and diff;
                                             exit 1 with the offending path and
                                             the first differing line

tokens.yaml is the only file in the organisation where a colour may be written
by hand. Everything below is derived from it, and gate A7 proves that on every
push. Before this existed the palette had two independent sources — the CSS
custom properties and 86 \\definecolor literals across two .sty files — kept in
agreement manually. They were not in agreement: Persian reached the CSS side and
never reached either .sty.

Output is deterministic: sorted where order is not meaningful, "\\n" endings, no
timestamps, no host paths. Regenerating on an unchanged input produces a
byte-identical file, which is what makes --check a usable gate rather than a
source of spurious diffs.

The website design page is written only when --website is given, because it
lives in a different repository.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import math
import itertools
from pathlib import Path

import yaml

KIT = Path(__file__).resolve().parent.parent
SRC = KIT / "design" / "tokens.yaml"

BANNER_HASH_LEN = 16


def load() -> tuple[dict, str]:
    raw = SRC.read_bytes()
    return yaml.safe_load(raw.decode("utf-8")), hashlib.sha256(raw).hexdigest()


def banner(comment: str, sha: str, closer: str = "") -> str:
    """Provenance header. A hand edit to a generated file is visible in review
    before CI catches it, which is the cheaper place to catch it."""
    return (
        f"{comment} GENERATED by design/build_tokens.py from "
        f"design/tokens.yaml@{sha[:BANNER_HASH_LEN]}. Do not edit.{closer}\n"
        f"{comment} Change the token in tokens.yaml and regenerate. Gate A7 "
        f"fails a hand edit here.{closer}\n"
    )


def resolve(t: dict, ref: str) -> dict:
    """Follow an `alias:` chain to the pair it points at."""
    node = t["colour"]
    if ref == "accent":                       # resolved per course at render time
        return {"light": "var(--boulingua-accent)", "dark": "var(--boulingua-accent)"}
    for part in ref.split("."):
        node = node[part]
    return resolve(t, node["alias"]) if "alias" in node else node


def pairs(t: dict) -> list[tuple[str, str, str]]:
    """(token-name, light, dark) for every colour, aliases already followed."""
    out: list[tuple[str, str, str]] = []
    for group, items in t["colour"].items():
        for name, v in items.items():
            key = name if group == "brand" else f"{group}-{name}"
            val = resolve(t, v["alias"]) if "alias" in v else v
            out.append((key, val["light"], val["dark"]))
    return out


_WORD = {"-": "minus", "0": "zero", "1": "one", "2": "two", "3": "three",
         "4": "four", "5": "five", "6": "six", "7": "seven", "8": "eight",
         "9": "nine"}


def texname(key: str) -> str:
    """A LaTeX control sequence may contain letters only, so \\blgspace0 parses
    as \\blgspace followed by a stray 0 and the length is never set. Spell the
    digits: 0 -> zero, -3 -> minusthree, 12 -> onetwo."""
    return "".join(_WORD.get(c, c) for c in key)


def latex_colours(t: dict) -> list[tuple[str, str]]:
    """(latex-name, light) for the colours print consumes. Only tokens that
    declare `latex:` cross over; the rest are web-only by design."""
    out: list[tuple[str, str]] = []
    for items in t["colour"].values():
        for v in items.values():
            if "latex" not in v:
                continue
            val = resolve(t, v["alias"]) if "alias" in v else v
            out.append((v["latex"], val["light"]))
    return sorted(out)


# ── artefact 1: CSS ─────────────────────────────────────────────────────────
def emit_css(t: dict, sha: str) -> str:
    p = t["meta"]["prefix"]
    L, D = [], []
    for name, light, dark in pairs(t):
        L.append(f"  --{p}-{name}: {light};")
        D.append(f"    --{p}-{name}: {dark};")
    for code, v in (("1", t["elevation"]["1"]), ("2", t["elevation"]["2"])):
        L.append(f"  --{p}-elev-{code}: {v['light']};")
        D.append(f"    --{p}-elev-{code}: {v['dark']};")
    for step, v in t["type"]["steps"].items():
        L.append(f"  --{p}-text-{step.replace('-', 'n')}: {v['rem']}rem;")
    for k, v in t["type"]["line_height"].items():
        L.append(f"  --{p}-leading-{k}: {v};")
    for k, v in t["type"]["tracking"].items():
        L.append(f"  --{p}-tracking-{k}: {v};")
    L.append(f"  --{p}-measure: {t['type']['measure']};")
    for k, v in t["space"].items():
        L.append(f"  --{p}-space-{k}: {v['rem']}rem;")
    for k, v in t["radius"].items():
        css = v.get("css") or f"{v['px']}px"
        L.append(f"  --{p}-radius-{k}: {css};")

    # Panel aliases. custom.css named three roles the token set already had.
    # These are permanent: they read better at the call site than the token
    # they resolve to, and they cost one line each.
    L += [
        f"  --{p}-panel-border: var(--{p}-border);",
        f"  --{p}-panel-border-hover: var(--{p}-accent);",
        f"  --{p}-panel-shadow: var(--{p}-elev-1);",
    ]

    # --network-* named the same roles as --boulingua-*. Aliased for one
    # release so the call sites migrate by tool, then deleted.
    alias = [
        f"  --network-surface: var(--{p}-surface);",
        f"  --network-border: var(--{p}-border);",
        f"  --network-fg-mute: var(--{p}-fg-muted);",
        f"  --network-rail-bg: var(--{p}-network-rail-bg);",
        f"  --network-highlight: var(--{p}-network-highlight);",
    ] + [f"  --network-topic-{k}: var(--{p}-topic-{k});" for k in sorted(t["colour"]["topic"])]

    nl = "\n"
    return (
        banner("/*", sha, " */")
        + f"""
:root {{
{nl.join(L)}

  /* Deprecated alias block. --network-* was a second namespace for roles that
     --boulingua-* already had. Retained for one release so `kit design migrate`
     can move the call sites; deleted after that. Do not add to it. */
{nl.join(alias)}
}}

@media (prefers-color-scheme: dark) {{
  body.colorscheme-auto {{
{nl.join(D)}
  }}
}}

body.colorscheme-dark {{
{nl.join(x.lstrip() and "  " + x.strip() for x in D)}
}}
"""
    )


# ── artefact 2: LaTeX ───────────────────────────────────────────────────────
def emit_sty(t: dict, sha: str) -> str:
    lines = [
        banner("%", sha),
        "\\NeedsTeXFormat{LaTeX2e}",
        "\\ProvidesPackage{boulingua-tokens}[boulingua design tokens]",
        "\\RequirePackage{xcolor}",
        "",
        "% Print takes the LIGHT value of every token. Paper has no dark mode,",
        "% and a deck projected in a dark room is still ink on a light ground.",
        "",
    ]
    for name, light in latex_colours(t):
        lines.append(f"\\definecolor{{{name}}}{{HTML}}{{{light.lstrip('#').upper()}}}")
    lines += ["", "% Per-language accents. \\blgsetlang{<code>} selects one.", ""]
    for a in t["accents"]:
        c = a["code"]
        lines.append(
            f"\\definecolor{{acc-{c}}}{{HTML}}{{{a['accent'].lstrip('#').upper()}}}"
            f"\\definecolor{{acch-{c}}}{{HTML}}{{{a['hover'].lstrip('#').upper()}}}"
            f"% {a['language']}"
        )
    lines += [
        "",
        "% Type scale. The pt values are the print side of the same steps the",
        "% web uses, so a caption is the same size on screen and on paper.",
        "",
    ]
    for step, v in t["type"]["steps"].items():
        lines.append(f"\\newcommand{{\\blgtext{texname(step)}}}{{\\fontsize{{{v['pt']}}}{{{round(v['pt'] * 1.35, 1)}}}\\selectfont}}")
    lines += ["", "% Space ramp, in points.", ""]
    for k, v in t["space"].items():
        n = texname(k)
        lines.append(f"\\newlength{{\\blgspace{n}}}\\setlength{{\\blgspace{n}}}{{{v['pt']}pt}}")
    lines += ["", "% Radius. 4px at 96dpi is exactly 3pt.", ""]
    for k, v in t["radius"].items():
        if v.get("pt") is not None:
            lines.append(f"\\newcommand{{\\blgradius{k}}}{{{v['pt']}pt}}")
    lines += [
        "",
        "% No elevation macros by design: print depth is rule weight, never blur.",
        "",
        "% \\tl{} — the print counterpart of the {{< tl >}} shortcode. For Latin,",
        "% Greek, Cyrillic and CJK it is the identity: those scripts need no",
        "% direction change and the glyphs come from the same face. It exists now,",
        "% as a no-op, so unit sources written today already carry the markup and do",
        "% not need a pass over every file when bidi lands at wave 5, where this is",
        "% redefined to \\textarabic{} / \\textpersian{}.",
        "\\providecommand{\\tl}[1]{#1}",
        "",
        "\\endinput",
        "",
    ]
    return "\n".join(lines)


# ── artefact 3: accents.yaml ────────────────────────────────────────────────
def emit_accents(t: dict, sha: str) -> str:
    out = [banner("#", sha),
           "# Consumed by layouts/_partials/head/extensions.html (accent injection),",
           "# brand/make_icon.py (the pentagon), and the generated footer sister list.",
           ""]
    for a in t["accents"]:
        out.append(f"- code: {a['code']}")
        out.append(f"  language: {json.dumps(a['language'])}")
        for k in ("accent", "hover", "dark", "dark_hover"):
            out.append(f'  {k}: "{a[k]}"')
        out.append(f"  published: {str(a['published']).lower()}")
        if a.get("note"):
            for chunk in _wrap(a["note"], 74):
                out.append(f"  # {chunk}")
    return "\n".join(out) + "\n"


def _wrap(s: str, w: int) -> list[str]:
    words, line, out = s.split(), "", []
    for x in words:
        if len(line) + len(x) + 1 > w:
            out.append(line); line = x
        else:
            line = f"{line} {x}".strip()
    if line:
        out.append(line)
    return out


# ── artefact 4: JSON ────────────────────────────────────────────────────────
def emit_json(t: dict, sha: str) -> str:
    doc = {
        "_generated_by": "design/build_tokens.py",
        "_source": f"design/tokens.yaml@{sha[:BANNER_HASH_LEN]}",
        "_warning": "Do not edit. Gate A7 fails a hand edit here.",
        "prefix": t["meta"]["prefix"],
        "colour": {n: {"light": l, "dark": d} for n, l, d in sorted(pairs(t))},
        "accents": {a["code"]: a for a in t["accents"]},
        "type": t["type"],
        "space": t["space"],
        "radius": t["radius"],
        "elevation": t["elevation"],
    }
    return json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# ── artefact 5: the public colour page ──────────────────────────────────────

# ── conformance, computed rather than claimed ───────────────────────────────
# The design page used to assert "at least 20° apart" and "WCAG AA on white".
# Neither was true: 10 of 18 accents fail AA on white and 13 pairs sit closer
# than 20° — eight of them closer than the 15° gate A10 actually enforces. A
# public design page claiming AA compliance it does not have is a false
# accessibility statement, and the fact that it was written as an aspiration
# does not change how a reader takes it. So the page now measures the palette
# it is printing and says what it finds. After S5 re-derives the accents the
# same code will print zero, without anybody remembering to edit a sentence.
def _lin(c: float) -> float:
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _lum(hx: str) -> float:
    r, g, b = (_lin(int(hx[i:i + 2], 16)) for i in (1, 3, 5))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: str, b: str) -> float:
    la, lb = _lum(a), _lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def oklch_hue(hx: str) -> float:
    r, g, b = (_lin(int(hx[i:i + 2], 16)) for i in (1, 3, 5))
    l = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b) ** (1 / 3)
    m = (0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b) ** (1 / 3)
    s2 = (0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b) ** (1 / 3)
    A = 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s2
    B = 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s2
    return math.degrees(math.atan2(B, A)) % 360


def conformance(accs: list[dict], floor: float = 15.0) -> dict:
    fails = [(a["code"], contrast(a["accent"], "#FFFFFF")) for a in accs
             if contrast(a["accent"], "#FFFFFF") < 4.5]
    hues = {a["code"]: oklch_hue(a["accent"]) for a in accs}
    close = []
    for x, y in itertools.combinations(sorted(hues), 2):
        d = abs(hues[x] - hues[y])
        d = min(d, 360 - d)
        if d < floor:
            close.append((x, y, d))
    return {"aa": sorted(fails, key=lambda z: z[1]),
            "close": sorted(close, key=lambda z: z[2]), "floor": floor}


def emit_design_md(t: dict, sha: str) -> str:
    rows = [
        f"| `{a['code']}` | {a['language']} | "
        f'<span style="color:{a["accent"]}">■</span> `{a["accent"]}` | `{a["hover"]}` | '
        f'<span style="color:{a["dark"]}">■</span> `{a["dark"]}` | `{a["dark_hover"]}` | '
        f"{'live' if a['published'] else 'planned'} |"
        for a in t["accents"] if a["code"] != "template"
    ]
    accs = [a for a in t["accents"] if a["code"] != "template"]
    conf = conformance(accs)
    if not conf["aa"] and not conf["close"]:
        conf_text = ("Nothing. Every accent clears 4.5:1 on white and no two sit "
                     f"closer than {conf['floor']:.0f}° apart.")
    else:
        parts = []
        if conf["aa"]:
            worst = ", ".join(f"`{c}` {r:.2f}:1" for c, r in conf["aa"][:4])
            parts.append(
                f"**{len(conf['aa'])} of {len(accs)} accents fall below 4.5:1 on "
                f"white** ({worst}{', …' if len(conf['aa']) > 4 else ''}). They are "
                f"legible, but they do not meet AA at body-text size. Naming "
                f"them here is the honest position while they are re-derived; "
                f"the alternative was a page that claimed compliance the "
                f"palette did not have.")
        if conf["close"]:
            worst = ", ".join(f"`{x}`/`{y}` {d:.1f}°" for x, y, d in conf["close"][:3])
            parts.append(
                f"**{len(conf['close'])} pairs sit closer than "
                f"{conf['floor']:.0f}°** ({worst}"
                f"{', …' if len(conf['close']) > 3 else ''}). The neighbouring "
                f"greens are the pressure point: English, French, Dutch and "
                f"Norwegian all want the same part of the wheel.")
        conf_text = "\n\n".join(parts)

    cefr = t["colour"]["cefr"]
    a_l, c_l = cefr["a"]["light"], cefr["c"]["light"]
    hub = t["colour"]["brand"]["hub"]["light"]
    return (
        banner("<!--", sha, " -->")
        + f"""---
title: "Design & colours"
description: "How boulingua chooses a colour for each language, and why."
---

Every boulingua course shares one design system — the same navigation, the same
typography, the same rhythm in light and dark. Within that frame each language
carries **one signature accent colour**, so a course is recognisable at a glance
without ever looking like a different product.

## The rules

A language's accent must be:

1. **Flag-safe.** The hue does not appear in that language's national flag.
   Colour should signal *which course you are in*, not which country a language
   is spoken in — a language is not a nation, and several of these are spoken
   across many.
2. **At least {conf["floor"]:.0f}° apart** from every other accent on the OKLCH hue
   wheel, so two courses are never mistaken for each other.
3. **WCAG AA on white** — 4.5:1 — because an accent is used for links and rules,
   not decoration.
4. **Not hub blue** — `{hub}` is reserved for this umbrella site and for
   anything that belongs to no single course.

### Where the palette does not meet them yet

These rules are the specification, and this section is measured from the same
file the table below is printed from — so it cannot quietly stop being true.

{conf_text}

## The palette

{len([a for a in t['accents'] if a['code'] != 'template'])} languages.

| Code | Language | Accent | Hover | Dark | Dark hover | Status |
|---|---|---|---|---|---|---|
""" + "\n".join(rows) + f"""

## CEFR levels

Independent of the accents and shared by every course, so a B1 badge means the
same thing everywhere: **A** `{a_l}` · **B** `{hub}` (hub blue) · **C** `{c_l}`.

## Where these come from

This page is generated. The colours live in one file — `design/tokens.yaml` in
the [kit](https://github.com/boulingua/kit) — from which the site CSS, the LaTeX
material templates, the accent registry and this table are all built. Adding a
nineteenth language is one entry there, not an edit in nineteen places.
""")


def patch_readme(t: dict, path: Path) -> str | None:
    """Replace the accent table in the website README between its markers.

    The table was hand-kept and had 17 rows against a registry of 18 — Persian
    was added to the data and to the world map and never reached the README.
    Fifteen more languages arrive in the build-out waves, and a table that must
    be edited fifteen more times will be wrong fifteen more times. A README
    cannot run Hugo templates, so it is patched between markers instead.
    """
    if not path.exists():
        return None
    body = path.read_text(encoding="utf-8")
    rows = "\n".join(
        f"| `{a['code']}` | {a['language']} | `{a['accent']}` | `{a['dark']}` |"
        for a in t["accents"] if a["code"] != "template")
    block = (BEGIN + "\n"
             "| Code | Language | Light accent | Dark accent |\n"
             "|------|----------|--------------|-------------|\n"
             + rows + "\n" + END)
    if BEGIN in body and END in body:
        head, rest = body.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    # First run: replace the existing hand-written table in place.
    lines, out, i, done = body.splitlines(True), [], 0, False
    while i < len(lines):
        if not done and lines[i].startswith("| Code | Language |"):
            while i < len(lines) and lines[i].startswith("|"):
                i += 1
            out.append(block + "\n")
            done = True
            continue
        out.append(lines[i]); i += 1
    return "".join(out) if done else None


BEGIN = "<!-- BEGIN generated accent table — design/build_tokens.py. Do not edit. -->"
END = "<!-- END generated accent table -->"


# ── driver ──────────────────────────────────────────────────────────────────
def show(p: Path) -> str:
    """Display path relative to the org checkout where possible, else absolute.
    The website repo is a sibling, so it is not always under KIT.parent."""
    try:
        return str(p.relative_to(KIT.parent))
    except ValueError:
        return str(p)


def artefacts(t: dict, sha: str, website: Path | None) -> dict[Path, str]:
    out = {
        KIT / "assets" / "css" / "tokens.css": emit_css(t, sha),
        KIT / "latex" / "boulingua-tokens.sty": emit_sty(t, sha),
        KIT / "data" / "accents.yaml": emit_accents(t, sha),
        KIT / "design" / "tokens.json": emit_json(t, sha),
    }
    if website:
        w = website.resolve()
        out[w / "content" / "design.md"] = emit_design_md(t, sha)
        readme = patch_readme(t, w / "README.md")
        if readme is not None:
            out[w / "README.md"] = readme
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff instead of writing; exit 1 on drift")
    ap.add_argument("--website", type=Path, default=None,
                    help="path to the website repo, to write content/design.md")
    a = ap.parse_args()

    t, sha = load()
    built = artefacts(t, sha, a.website)

    if a.check:
        bad = 0
        for path, want in built.items():
            rel = show(path)
            if not path.exists():
                print(f"::error::{rel} is missing — run design/build_tokens.py")
                bad += 1
                continue
            have = path.read_text(encoding="utf-8")
            if have != want:
                for i, (h, w) in enumerate(zip(have.splitlines(), want.splitlines()), 1):
                    if h != w:
                        print(f"::error::{rel}:{i} differs from tokens.yaml")
                        print(f"  on disk:   {h.strip()[:100]}")
                        print(f"  generated: {w.strip()[:100]}")
                        break
                else:
                    print(f"::error::{rel} differs in length from tokens.yaml")
                bad += 1
        if bad:
            print(f"\nA7 FAIL — {bad} generated file(s) edited by hand. Change the "
                  f"token in design/tokens.yaml and regenerate.", file=sys.stderr)
            return 1
        print(f"A7 OK — {len(built)} generated artefacts match design/tokens.yaml")
        return 0

    for path, text in built.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"  {show(path)}  ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
